#██████╗ ███╗   ███╗███████╗███████╗███████╗███████╗███╗   ██╗████████╗██╗ █████╗ ██╗     ███████╗
#██╔══██╗████╗ ████║██╔════╝██╔════╝██╔════╝██╔════╝████╗  ██║╚══██╔══╝██║██╔══██╗██║     ██╔════╝
#██████╔╝██╔████╔██║█████╗  ███████╗███████╗█████╗  ██╔██╗ ██║   ██║   ██║███████║██║     ███████╗
#██╔═══╝ ██║╚██╔╝██║██╔══╝  ╚════██║╚════██║██╔══╝  ██║╚██╗██║   ██║   ██║██╔══██║██║     ╚════██║
#██║     ██║ ╚═╝ ██║███████╗███████║███████║███████╗██║ ╚████║   ██║   ██║██║  ██║███████╗███████║
#╚═╝     ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝
cfg-version: 1 # don't touch this

# built-in cooldowns: (in seconds)
heal.cooldown: 300
feed.cooldown: 120
back.cooldown: 60
smite.cooldown: 300
extinguish.cooldown: 180
milk.cooldown: 120

# timeout for teleport request (in seconds)
tpa.timeout: 120
